version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: middleware_db
      POSTGRES_USER: midwr
      POSTGRES_PASSWORD: 12987wq
#      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - /tmp:/var/lib/postgresql/data2
    ports:
      - "6543:5432"
