version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: middleware_db
      POSTGRES_USER: midwr
      POSTGRES_PASSWORD: 12987wq
    volumes:
      - /tmp:/var/lib/postgresql/data
    ports:
      - "8080:8080"
